version: "3.8"

services:
  db:
    container_name: mysql
    image: mysql
    environment:
      # Use ROOT password for simplicity since you specified user 'root' in Flask
      MYSQL_ROOT_PASSWORD: Rohith@2006
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306" # FIXED: MySQL uses 3306, not 5000
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - flask-db-net
    restart: always

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/static
    container_name: flask-app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: Rohith@2006
      MYSQL_DB: mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - db 
    networks:
      - flask-db-net
    restart: always

volumes:
  mysql-data:

networks:
  flask-db-net: